### ISSUE TITLE
redemption widget - I need to wait 15 sec to see the first page appearing (wallet dependant)

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/widgets#112]
![image](https://github.com/bosonprotocol/widgets/assets/7184124/2ad98263-eeb4-4ff7-9c1a-ca3fc7e5e822)

**Comment by levalleux-ludo** [comment]
fixes by https://github.com/bosonprotocol/core-components/pull/642

**Comment by sukrita3** [comment]
looks ok when I tested
