### ISSUE TITLE
reconsider use of email or XMTP preference for the redemption info

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/widgets#114]
At the moment, the redeem widget code suggests the email to be required only when the contact preference of the seller is set to "xmtp_and_email".
If the contact preference is "xmtp", the email is asked but not required.

However, the current implementation fails in doing that in most case.
The following PR https://github.com/bosonprotocol/core-components/pull/642 forces the email to be always required.

This issue is opened to raise that point and reconsider whether or not we want to achieve the initially expected behaviour

**Comment by levalleux-ludo** [comment]
Rework of the PR https://github.com/bosonprotocol/core-components/pull/642 now keeps the original behaviour, fixing the issue

**Comment by sukrita3** [comment]
Not sure what was changed here, as I am still always asked for email in the redemption form.
